---
- include_vars: vault_config.yml

- name: copy ssh config
  copy: content="{{dotconfig}}" dest=/home/saga/.ssh/config owner=saga group=saga mode=400

- name: copy id_rsa_yahoo_pub
  copy: content="{{id_rsa_yahoo_pub}}" dest=/home/saga/.ssh/id_rsa_yahoo.pub owner=saga group=saga mode=400

- name: copy id_rsa_yahoo
  copy: content="{{id_rsa_yahoo}}" dest=/home/saga/.ssh/id_rsa_yahoo owner=saga group=saga mode=400

- name: copy id_rsa
  copy: content="{{id_rsa}}" dest=/home/saga/.ssh/id_rsa owner=saga group=saga mode=400

- name: copy id_rsa_pub
  copy: content="{{id_rsa_pub}}" dest=/home/saga/.ssh/id_rsa.pub owner=saga group=saga mode=400

- name: copy id_rsa_fedora
  copy: content="{{id_rsa_fedora}}" dest=/home/saga/.ssh/id_rsa_fedora owner=saga group=saga mode=400

- name: copy id_rsa_fedora_pub
  copy: content="{{id_rsa_fedora_pub}}" dest=/home/saga/.ssh/id_rsa_fedora.pub owner=saga group=saga mode=400

- name: copy id_rsa_docean
  copy: content="{{id_rsa_docean}}" dest=/home/saga/.ssh/id_rsa_docean owner=saga group=saga mode=400

- name: copy id_rsa_fedora_pub
  copy: content="{{id_rsa_docean_pub}}" dest=/home/saga/.ssh/id_rsa_docean.pub owner=saga group=saga mode=400
