---
- include_vars: vault_config.yml

- name: copy ssh config
  copy: content="{{dotconfig}}" dest=/home/{{ansible_user}}/.ssh/config owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_yahoo_pub
  copy: content="{{id_rsa_yahoo_pub}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_yahoo.pub owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_yahoo
  copy: content="{{id_rsa_yahoo}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_yahoo owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa
  copy: content="{{id_rsa}}" dest=/home/{{ansible_user}}/.ssh/id_rsa owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_pub
  copy: content="{{id_rsa_pub}}" dest=/home/{{ansible_user}}/.ssh/id_rsa.pub owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_fedora
  copy: content="{{id_rsa_fedora}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_fedora owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_fedora_pub
  copy: content="{{id_rsa_fedora_pub}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_fedora.pub owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_docean
  copy: content="{{id_rsa_docean}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_docean owner={{ansible_user}} group={{ansible_user}} mode=400

- name: copy id_rsa_fedora_pub
  copy: content="{{id_rsa_docean_pub}}" dest=/home/{{ansible_user}}/.ssh/id_rsa_docean.pub owner={{ansible_user}} group={{ansible_user}} mode=400
