---
- name: Install vim
  yum: name=vim-enhanced state=present
  tags: vim

- name: Setup .vim/autoload
  file: path=/home/saga/.vim/autoload state=directory owner=saga group=saga mode=0755 recurse=yes
  tags: vim

- name: Setup .vim/bundle
  file: path=/home/saga/.vim/bundle state=directory owner=saga group=saga mode=0755
  tags: vim

- name: Is vim-jedi installed
  shell: "[ -d /home/saga/.vim/bundle/jedi-vim ]"
  register: jedi_vim_installed
  ignore_errors: True
  changed_when: jedi_vim_installed|failed

- name: Is vim-flake8 installed
  shell: "[ -d /home/saga/.vim/bundle/vim-flake8 ]"
  register: vim_flake8_installed
  ignore_errors: True
  changed_when: vim_flake8_installed|failed

- name: Setup pathogen
  get_url: 
    url: https://tpo.pe/pathogen.vim
    dest: /home/saga/.vim/autoload/pathogen.vim 
    mode: 0644
    owner: saga
    group: saga

- name: Setup vim-jedi
  git: repo=https://github.com/davidhalter/jedi-vim.git dest=/home/saga/.vim/bundle/
  become: yes
  become_user: saga
  tags: vim
  when: jedi_vim_installed|failed

- name: Setup vim-flake8
  git: repo=https://github.com/nvie/vim-flake8.git dest=/home/saga/.vim/bundle/
  become: yes
  become_user: saga
  tags: vim
  when: vim_flake8_installed|failed

- name: Copy vimrc
  copy: src=vimrc dest=/home/saga/.vimrc owner=saga group=saga mode=644
  tags: vim
